### ISSUE TITLE
Failed to recover backups

### ISSUE THREAD

**Issue by VirtualW** [YoeriNijs/NoteBuddy#15]
My friend:
I enjoyed your app for quite some time because it has just what I needed, no more, no less.

However I just discovered that it has a terrible mistake.
While I was tidying my things I was calm because I had backed up all my notes.
But I was very surprised to find that Notebuddy is unable to read them after a reinstall.

I thought it was a mistake of mine to make a mistake with the username (the password was used daily) but I saw that it was not the case as I tried completely new and simple accounts and notes on two different Android devices, always checking that the application only it recognizes the title but not the content when resetting or reinstalling it, regardless of whether the login details were correct.

Please, I would appreciate it if you would review this error as we trust your application to protect our information. Losing everything despite having backups is hopeless.

It would be recommended that you update your excellent tool with the error fixed so that we can recover all the previous work and continue working with it, who are already used to its great performance.

I would appreciate it if you could keep the community informed if this can be remedied or we should lose hope.

Thank you!

**Comment by YoeriNijs** [comment]
Thank you for your response. 

Well, actually this is not an error. When you set up NoteBuddy, the app creates an unique salt that is bound to the current NoteBuddy installation. When you backup your files, the files are encrypted by the provided password (that only you know) and by the unique salt. When you re-install your application, there is a new salt created and, as a consequence, it is not possible to read the files again (because the combination of your password and the new salt is not the same as the previous combination). Hence, the content of the files is empty (i.e. not visible, because you cannot decrypt them).

So, what you have to do when you want to 'share' the notes between multiple installations, is to decrypt your files by creating a backup and select the option 'decrypted'. Then, you can copy your files, save them somewhere on your Android device, and later paste them in the external data folder of the new NoteBuddy installation. Subsequently, you can import the plain-text files again. When you do this, NoteBuddy is able to encrypt the files again with your password and the new salt. In the end, click on 'Clear backup storage' to wipe the plain-text files, so you only have the encrypted files again.

Currently, I am planning a complete rewrite of NoteBuddy, where I am trying to create a better explanation about what the backup possibilities are the riscs are. It is important to state, however, that the new release will probably be a breaking change. When this is the case, NoteBuddy 2.x will be releases as separate app, and the old 1.x release will be removed from the Play Store, so no one can download the application anymore. However, if you have installed it on your phone, you can still use it. If you then want to share your notes, you have to use the previous stated steps.

**Comment by VirtualW** [comment]
Thanks for the reply. 
The backup always gave the option to choose between "encrypted" or "decrypted". I never imagined that this backup could not be read by a new installation. There was no warning.
I can not believe it. All lost ...
Thank you as well.
